repository: csyphil/BYR-Navi
repository_url: https://github.com/csyphil/BYR-Navi

timezone: Asia/Shanghai
lang: zh_CN

title: 夕岚导航 · XiLan-Navi
alias_en: XiLan-Navi
alias_cn: 夕岚导航
description: A Navigation Website for XiLan
keywords: 夕岚导航, XiLan-Navi, Navi, Navigation
url: https://google.philsilver.xyz
established_at: "2021-08-06T00:00+08:00"

author: PhilSilver
author_url: https://philsilver.xyz
organization: XiLan
organization_url: https://google.philsilver.xyz
contact: contact[at]philsilver[dot]xyz

image: /images/logo.png
logo: /images/logo.png
logo_dark: /images/logo-dark.svg
logo_white: /images/logo-white.svg


plugins:
- jekyll-seo-tag
- jekyll-sitemap

exclude:
- .gitignore
- .travis.yml
- LICENSE
- README.md
- CNAME
- Gemfile
- Gemfile.lock
- script
- vendor
